import FetchCore

public enum HuggingFaceAuditCorpus {
    public static let tinyStoriesSource = GutenbergMiniCorpus.Source(
        datasetID: "roneneldan/TinyStories",
        config: "default",
        split: "train",
        license: "CDLA-Sharing-1.0; synthetic short stories generated by GPT-3.5 and GPT-4",
        url: "https://huggingface.co/datasets/roneneldan/TinyStories"
    )

    public static let simpleWikipediaSource = GutenbergMiniCorpus.Source(
        datasetID: "juno-labs/simple_wikipedia",
        config: "default",
        split: "train",
        license: "CC-BY-SA-3.0",
        url: "https://huggingface.co/datasets/juno-labs/simple_wikipedia"
    )

    public static let gutenbergPoetrySource = GutenbergMiniCorpus.Source(
        datasetID: "biglam/gutenberg-poetry-corpus",
        config: "default",
        split: "train",
        license: "CC0-1.0",
        url: "https://huggingface.co/datasets/biglam/gutenberg-poetry-corpus"
    )

    public static let records: [FetchDocumentRecord] = tinyStoriesRecords
        + simpleWikipediaRecords
        + gutenbergPoetryRecords

    public static let tinyStoriesRecords: [FetchDocumentRecord] = [
        FetchDocumentRecord(
            id: "hf-tinystories-row-4-cobweb",
            title: "Lily Cleans a Castle Cobweb",
            body: """
            Lily liked to pretend she was a popular princess in a big castle with her cat and dog. While playing, she found a cobweb that blocked her game.

            Lily was scared of the spider living there, so she asked her friends to help. Together, the cat, the dog, and Lily cleaned the cobweb, and the spider found a new home outside.
            """,
            kind: .article,
            language: "en",
            sourceURI: tinyStoriesSource.url,
            metadata: sourceMetadata(tinyStoriesSource, row: "4", topic: "cobweb")
        ),
        FetchDocumentRecord(
            id: "hf-tinystories-row-5-kayak",
            title: "The Brown Kayak Rolls in the Lake",
            body: """
            In a big lake, a brown kayak liked to roll in the water all day. A little boy named Tim came to play, and they rolled together in the warm lake.

            When Tim went home, the kayak was sad but kept rolling in the water while waiting for another fun day.
            """,
            kind: .article,
            language: "en",
            sourceURI: tinyStoriesSource.url,
            metadata: sourceMetadata(tinyStoriesSource, row: "5", topic: "kayak")
        ),
        FetchDocumentRecord(
            id: "hf-tinystories-row-6-triangle",
            title: "Lily Finds Her Triangle",
            body: """
            Lily was troubled because she lost her favorite toy, a triangle. She searched her house, then went to the park and looked in a puddle.

            Lily reached into the water and found the triangle at the bottom. After that, puddles reminded her of finding the toy she loved.
            """,
            kind: .article,
            language: "en",
            sourceURI: tinyStoriesSource.url,
            metadata: sourceMetadata(tinyStoriesSource, row: "6", topic: "toy")
        ),
        FetchDocumentRecord(
            id: "hf-tinystories-row-7-race",
            title: "Tim and Sarah Run a Race",
            body: """
            Tim loved to run and play outside. He saw a race in the park and asked Sarah to start the race with him.

            They waited for the word go, then ran with the wind in their hair. Tim reached the finish line first, Sarah came second, and both celebrated with friends.
            """,
            kind: .article,
            language: "en",
            sourceURI: tinyStoriesSource.url,
            metadata: sourceMetadata(tinyStoriesSource, row: "7", topic: "race")
        ),
    ]

    public static let simpleWikipediaRecords: [FetchDocumentRecord] = [
        FetchDocumentRecord(
            id: "hf-simplewiki-april",
            title: "April",
            body: """
            **April** is the fourth month of the year in the Julian and Gregorian calendars. It comes between March and May, has 30 days, and is a spring month in the Northern Hemisphere.

            ## The Month

            April begins on the same day of the week as July every year and on the same day as January in leap years. It ends on the same day of the week as December.

            ## April in poetry

            Poets use April to mean the end of winter, as in the saying that April showers bring May flowers.
            """,
            contentType: .markdown,
            kind: .reference,
            language: "en",
            sourceURI: simpleWikipediaSource.url,
            metadata: sourceMetadata(simpleWikipediaSource, row: "0", topic: "calendar")
        ),
        FetchDocumentRecord(
            id: "hf-simplewiki-ad-hominem",
            title: "Ad hominem",
            body: """
            **Ad hominem** is a Latin term for a type of argument. It is often used in rhetoric, the science of speaking well and convincing other people.

            Translated to English, ad hominem means against the person. It happens when someone attacks the person they are arguing against instead of answering what the person is saying.

            It is usually considered a weak and poor argument, especially in courts and diplomacy.
            """,
            contentType: .markdown,
            kind: .reference,
            language: "en",
            sourceURI: simpleWikipediaSource.url,
            metadata: sourceMetadata(simpleWikipediaSource, row: "18", topic: "rhetoric")
        ),
        FetchDocumentRecord(
            id: "hf-simplewiki-angels",
            title: "Angel",
            body: """
            **Angels** are described in many religious traditions as spirits or messengers. Some stories describe angels delivering messages, protecting people, or appearing in visions.

            ## Types of Angels

            Cherubs are described as winged creatures. Seraphs are associated with singing and praising God. Archangels such as Gabriel and Michael are described as important messengers.

            ## In art

            Angels are often shown with wings and a halo. The wings represent speed, and the halo represents holiness.
            """,
            contentType: .markdown,
            kind: .reference,
            language: "en",
            sourceURI: simpleWikipediaSource.url,
            metadata: sourceMetadata(simpleWikipediaSource, row: "17", topic: "religion")
        ),
    ]

    public static let gutenbergPoetryRecords: [FetchDocumentRecord] = [
        FetchDocumentRecord(
            id: "hf-poetry-hiawatha-source",
            title: "The Song of Hiawatha: Source Traditions",
            body: """
            The Song of Hiawatha is based on legends and stories of many North American Indian tribes, especially the Ojibway Indians of northern Michigan, Wisconsin, and Minnesota.

            The material was collected by Henry Rowe Schoolcraft and later used by Longfellow as a basis for the poem.
            """,
            kind: .article,
            language: "en",
            sourceURI: gutenbergPoetrySource.url,
            metadata: sourceMetadata(gutenbergPoetrySource, row: "0-18", topic: "hiawatha")
        ),
        FetchDocumentRecord(
            id: "hf-poetry-hiawatha-northland",
            title: "The Song of Hiawatha: Northland Images",
            body: """
            From the forests and the prairies,
            From the great lakes of the Northland,
            From the land of the Ojibways,
            From the land of the Dacotahs,
            From the mountains, moors, and fen-lands,
            Where the heron feeds among the reeds and rushes.
            """,
            kind: .article,
            language: "en",
            sourceURI: gutenbergPoetrySource.url,
            metadata: sourceMetadata(gutenbergPoetrySource, row: "40-46", topic: "northland")
        ),
        FetchDocumentRecord(
            id: "hf-poetry-hiawatha-firefly",
            title: "The Song of Hiawatha: Firefly",
            body: """
            Wah-wah-taysee, little fire-fly,
            Little, flitting, white-fire insect,
            Little, dancing, white-fire creature,
            Light me with your little candle,
            Ere upon my bed I lay me.
            """,
            kind: .article,
            language: "en",
            sourceURI: gutenbergPoetrySource.url,
            metadata: sourceMetadata(gutenbergPoetrySource, row: "24-29", topic: "firefly")
        ),
    ]

    private static func sourceMetadata(
        _ source: GutenbergMiniCorpus.Source,
        row: String,
        topic: String
    ) -> [String: String] {
        [
            "fixture.dataset": source.datasetID,
            "fixture.config": source.config,
            "fixture.split": source.split,
            "fixture.row": row,
            "fixture.topic": topic,
        ]
    }
}
