import FetchCore

public enum TinyStoriesMiniCorpus {
    public static let source = GutenbergMiniCorpus.Source(
        datasetID: "roneneldan/TinyStories",
        config: "default",
        split: "train",
        license: "CDLA-Sharing-1.0; synthetic short stories generated by GPT-3.5 and GPT-4",
        url: "https://huggingface.co/datasets/roneneldan/TinyStories"
    )

    public static let records: [FetchDocumentRecord] = [
        FetchDocumentRecord(
            id: "tinystories-row-0-needle",
            title: "Lily Shares a Needle",
            body: """
            One day, a little girl named Lily found a needle in her room. She knew it was difficult to play with it because it was sharp. Lily wanted to share the needle with her mom, so she could sew a button on her shirt.

            Lily went to her mom and said, "Mom, I found this needle. Can you share it with me and sew my shirt?" Her mom smiled and said, "Yes, Lily, we can share the needle and fix your shirt."

            Together, they shared the needle and sewed the button on Lily's shirt. It was not difficult for them because they were sharing and helping each other.
            """,
            kind: .article,
            language: "en",
            sourceURI: source.url,
            metadata: [
                "fixture.dataset": source.datasetID,
                "fixture.config": source.config,
                "fixture.split": source.split,
                "fixture.row": "0",
                "fixture.topic": "sewing",
            ]
        ),
        FetchDocumentRecord(
            id: "tinystories-row-1-beep",
            title: "Beep Plays in Falling Leaves",
            body: """
            Once upon a time, there was a little car named Beep. Beep loved to go fast and play in the sun. Beep was a healthy car because he always had good fuel.

            One day, Beep was driving in the park when he saw a big tree. The tree had many leaves that were falling. Beep liked how the leaves fall and wanted to play with them.

            When it was time to go home, Beep knew he needed more fuel. He went to the fuel place and got more healthy fuel.
            """,
            kind: .article,
            language: "en",
            sourceURI: source.url,
            metadata: [
                "fixture.dataset": source.datasetID,
                "fixture.config": source.config,
                "fixture.split": source.split,
                "fixture.row": "1",
                "fixture.topic": "car",
            ]
        ),
        FetchDocumentRecord(
            id: "tinystories-row-2-fin",
            title: "Fin Helps a Cold Crab",
            body: """
            One day, a little fish named Fin was swimming near the shore. He saw a big crab and wanted to be friends. The crab looked at Fin and said he was cold and did not feel fine.

            Fin wanted to help the crab feel better. He called to the sun, asking it to help his new friend feel fine and not freeze.

            The sun shone warm light on the shore. The crab started to feel better, thanked Fin, and played with him.
            """,
            kind: .article,
            language: "en",
            sourceURI: source.url,
            metadata: [
                "fixture.dataset": source.datasetID,
                "fixture.config": source.config,
                "fixture.split": source.split,
                "fixture.row": "2",
                "fixture.topic": "shore",
            ]
        ),
    ]
}
